{{- if or .Values.tlsBundle.certfile .Values.tlsBundle.keyfile .Values.tlsBundle.rootcafile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watcher.fullname" . }}-tls-bundle
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
    app.kubernetes.io/component: watcher
type: Opaque
data:
  {{- if .Values.tlsBundle.certfile }}
  certfile.pem: {{ .Values.tlsBundle.certfile }}
  {{- end }}
  {{- if .Values.tlsBundle.keyfile }}
  keyfile.pem: {{ .Values.tlsBundle.keyfile }}
  {{- end }}
  {{- if .Values.tlsBundle.rootcafile }}
  rootcafile.pem: {{ .Values.tlsBundle.rootcafile }}
  {{- end }}
{{- end }}
