# Generated by Django 5.0.11 on 2025-06-27 15:48

import django.utils.timezone
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MISPEventUuidLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('misp_event_uuid', django_mysql.models.ListCharField(models.CharField(max_length=36), blank=True, max_length=370, null=True, size=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain MISP Mapping',
                'verbose_name_plural': 'Domain MISP Mappings',
            },
        ),
    ]
