# Generated by Django 5.2.3 on 2025-10-28 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegitimateDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('ticket_id', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('repurchased', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('misp_event_uuid', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
