# Generated by Django 5.2.11 on 2026-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_legitimatedomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='legitimatedomain',
            name='ssl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
