# Generated by Django 6.0.5 on 2026-06-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_pendingaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legitimatedomain',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legitimate Domain', 'verbose_name_plural': 'Legitimate Domains'},
        ),
    ]
