# Generated by Django 6.0.5 on 2026-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_legitimatedomain_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(choices=[('udrp_transfer', 'UDRP - Transfer domain to Legitimate Domains'), ('connector_health_check', 'Connector - Health check failed')], max_length=50),
        ),
    ]
