# Generated by Django 6.0.6 on 2026-09-14 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_pendingaction_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDedupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=50)),
                ('dedup_key', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notification Dedup Entry',
                'verbose_name_plural': 'Notification Dedup Entries',
                'indexes': [models.Index(fields=['app_name', 'notification_type', 'dedup_key', 'sent_at'], name='common_noti_app_nam_58de53_idx')],
            },
        ),
    ]
