# Generated by Django 3.1.3 on 2020-11-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_leak', '0008_auto_20200403_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['name'], 'verbose_name_plural': 'Keywords Monitored'},
        ),
    ]
