# Generated by Django 5.2.11 on 2026-02-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_leak', '0011_alter_subscriber_options_subscriber_citadel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_regex',
            field=models.BooleanField(default=False, verbose_name='Use RegEx'),
        ),
    ]
