# Generated by Django 5.2.13 on 2026-04-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_leak', '0012_keyword_is_regex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['name'], 'verbose_name_plural': 'Search Patterns'},
        ),
    ]
