# Generated by Django 6.0.5 on 2026-07-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorHealthCheck',
            fields=[
                ('connector_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('healthy', models.BooleanField(default=None, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Connector Health Check',
                'verbose_name_plural': 'Connector Health Checks',
            },
        ),
    ]
