# Generated by Django 6.0.5 on 2026-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_connectorhealthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoroverride',
            name='auto_seeded_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
