# Generated by Django 3.0.2 on 2020-03-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0002_threats_watcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendyword',
            options={'ordering': ['-created_at']},
        ),
    ]
