# Generated by Django 3.1.1 on 2020-11-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0009_auto_20200526_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedword',
            options={'verbose_name': 'Blocklist', 'verbose_name_plural': 'Blocklist'},
        ),
    ]
