# Generated by Django 3.1.4 on 2021-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0011_auto_20201123_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturl',
            name='url',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=350),
        ),
    ]
