# Generated by Django 5.0.2 on 2024-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0013_auto_20210517_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=350, unique=True),
        ),
    ]
