# Generated by Django 5.0.9 on 2024-11-29 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0014_alter_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='citadel',
            field=models.BooleanField(default=False, verbose_name='Citadel'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.BooleanField(default=False, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='slack',
            field=models.BooleanField(default=False, verbose_name='Slack'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='thehive',
            field=models.BooleanField(default=False, verbose_name='TheHive'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats_watcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
