# Generated by Django 5.0.11 on 2025-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0015_subscriber_citadel_subscriber_email_subscriber_slack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='confident',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trendyword',
            name='score',
            field=models.FloatField(default=0, help_text='Average confidence score from source (1=100%, 2=50%, 3=20%)'),
        ),
    ]
