# Generated by Django 5.0.11 on 2025-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0015_subscriber_citadel_subscriber_email_subscriber_slack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='confident',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trendyword',
            name='fiability_score',
            field=models.IntegerField(default=0),
        ),
    ]
