# Generated by Django 5.0.11 on 2025-03-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0016_source_confident_trendyword_fiability_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturl',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
