# Generated by Django 5.2.3 on 2025-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0016_source_confident_trendyword_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=750, unique=True),
        ),
    ]
