# Generated by Django 5.2.13 on 2026-04-28 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0018_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='country',
            field=models.CharField(blank=True, help_text="Country this RSS source primarily covers (e.g. 'France', 'United States')", max_length=100),
        ),
        migrations.AddField(
            model_name='source',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code (e.g. 'FR', 'US')", max_length=2),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='notify_breaking_news',
            field=models.BooleanField(default=True, verbose_name='Breaking News'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='notify_monitored_keywords',
            field=models.BooleanField(default=True, verbose_name='Monitored Keywords'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='notify_trendy_words',
            field=models.BooleanField(default=True, verbose_name='Trendy Words'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='notify_weekly_summary',
            field=models.BooleanField(default=True, verbose_name='Weekly Summary'),
        ),
        migrations.CreateModel(
            name='MonitoredKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('level', models.CharField(choices=[('warm', 'Warm'), ('hot', 'Hot'), ('super_hot', 'Super Hot')], default='warm', help_text='Auto-computed from occurrence count, can be overridden', max_length=20)),
                ('threshold', models.IntegerField(default=1, help_text='Number of RSS occurrences needed to escalate to next level')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('occurrences', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posturls', models.ManyToManyField(blank=True, help_text='RSS article URLs where this keyword was detected', to='threats_watcher.posturl')),
            ],
            options={
                'ordering': ['-occurrences', 'name'],
            },
        ),
    ]
