# Generated by Django 5.2.9 on 2026-01-27 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0018_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyword',
            name='is_monitored',
            field=models.BooleanField(default=False, help_text='Indicates if this word is from a monitored keyword with boosted weight'),
        ),
        migrations.AddField(
            model_name='trendyword',
            name='monitored_temperature',
            field=models.CharField(blank=True, help_text='Temperature level if monitored (WARN, HOT, SUPER_HOT)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MonitoredKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('temperature', models.CharField(choices=[('WARN', 'Warn'), ('HOT', 'Hot'), ('SUPER_HOT', 'Super Hot')], default='WARN', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_detections', models.IntegerField(default=0)),
                ('last_detected_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_keywords', to=settings.AUTH_USER_MODEL)),
                ('posturls', models.ManyToManyField(blank=True, related_name='monitored_keywords', to='threats_watcher.posturl')),
            ],
            options={
                'verbose_name': 'Monitored Keyword',
                'verbose_name_plural': 'Monitored Keywords',
                'ordering': ['-created_at'],
            },
        ),
    ]
