# Generated by Django 6.0.5 on 2026-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats_watcher', '0019_source_country_source_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last fetch attempt', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_status_code',
            field=models.IntegerField(blank=True, help_text='HTTP status code returned during the last fetch attempt (e.g. 200, 404, SSL error → 0)', null=True),
        ),
    ]
