# Generated by Django 3.0.8 on 2020-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_finder', '0002_auto_20200804_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnstwisted',
            name='fuzzer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
