# Generated by Django 3.1 on 2020-08-31 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dns_finder', '0003_dnstwisted_fuzzer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_finder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
