# Generated by Django 3.1.3 on 2020-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_finder', '0005_auto_20201123_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnstwisted',
            name='misp_event_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dnstwisted',
            name='the_hive_case_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
