# Generated by Django 5.0.11 on 2025-05-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_finder', '0008_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnstwisted',
            name='misp_event_id',
        ),
    ]
