# Generated by Django 5.2.9 on 2026-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_finder', '0009_remove_dnstwisted_misp_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnstwisted',
            name='dangling_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Dangling Check'),
        ),
        migrations.AddField(
            model_name='dnstwisted',
            name='dangling_cname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNAME Record'),
        ),
        migrations.AddField(
            model_name='dnstwisted',
            name='dangling_info',
            field=models.TextField(blank=True, null=True, verbose_name='Dangling Details'),
        ),
        migrations.AddField(
            model_name='dnstwisted',
            name='dangling_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('safe', 'Safe'), ('exploitable', 'Could Be Exploitable'), ('takeover_possible', 'Takeover Likely Possible')], default='unknown', max_length=20, verbose_name='Dangling DNS Status'),
        ),
    ]
