# Generated by Django 6.0.6 on 2026-09-10 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_finder', '0009_remove_dnstwisted_misp_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanglingSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cname_target', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending check'), ('ok', 'OK'), ('dangling_suspected', 'Dangling suspected'), ('dangling_confirmed', 'Dangling confirmed'), ('resolved', 'Resolved'), ('false_positive', 'False positive')], default='pending', max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('dns_monitored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_finder.dnsmonitored')),
            ],
            options={
                'verbose_name': 'Dangling Subdomain',
                'verbose_name_plural': 'Dangling Subdomains',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='DanglingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='certstream', max_length=50)),
                ('dangling_subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_finder.danglingsubdomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
