# Generated by Django 6.0.5 on 2026-09-22 16:45

from django.db import migrations, models


DETECTION_STATUS_TO_ALERT_STATUS = {
    'pending': 'pending',
    'ok': 'resolved',
    'dangling_suspected': 'suspected',
    'dangling_confirmed': 'confirmed',
    'resolved': 'resolved',
    'false_positive': 'false_positive',
}


def backfill_alert_status(apps, schema_editor):
    """
    Backfill Alert.status through a temporary status_new column, since a
    straight BooleanField -> CharField AlterField would let MySQL cast the
    raw 0/1 storage into '0'/'1' strings instead. subdomain_takeover rows
    with a historical detection_status use the precise mapping above;
    everything else falls back to the old boolean (True -> pending,
    False -> resolved).
    """
    Alert = apps.get_model('dns_finder', 'Alert')

    for old_value, new_value in DETECTION_STATUS_TO_ALERT_STATUS.items():
        Alert.objects.filter(
            source='subdomain_takeover', dns_twisted__detection_status=old_value
        ).update(status_new=new_value)

    Alert.objects.filter(status_new__isnull=True, status=True).update(status_new='pending')
    Alert.objects.filter(status_new__isnull=True, status=False).update(status_new='resolved')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dns_finder', '0014_merge_dangling_into_alert_dnstwisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status_new',
            field=models.CharField(
                blank=True, null=True, max_length=20,
                choices=[
                    ('pending', 'Pending'), ('suspected', 'Suspected'), ('confirmed', 'Confirmed'),
                    ('resolved', 'Resolved'), ('false_positive', 'False Positive'),
                ],
            ),
        ),
        migrations.RunPython(backfill_alert_status, noop_reverse),
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='status_new',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(
                max_length=20, default='pending',
                choices=[
                    ('pending', 'Pending'), ('suspected', 'Suspected'), ('confirmed', 'Confirmed'),
                    ('resolved', 'Resolved'), ('false_positive', 'False Positive'),
                ],
            ),
        ),
        migrations.AddField(
            model_name='alert',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='dnstwisted',
            name='detection_status',
        ),
    ]
