services:
  db_watcher:
    init: true
    ports:
      - "127.0.0.1:${DB_WATCHER_PORT}:3306"
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db_watcher/data:/var/lib/mysql"
      - "./db_watcher/logs:/var/log/mysql"
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - watcher_network

networks:
  watcher_network:
    external: true
    name: ${NETWORK_NAME}
