# Generated by Django 6.0.5 on 2026-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
