# Generated by Django 5.2.13 on 2026-04-28 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('references', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CVE Alert',
                'verbose_name_plural': 'CVE Alerts',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='RansomwareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='ransomware.live', max_length=50)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ransomware Group',
                'verbose_name_plural': 'Ransomware Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label or case name for this rule', max_length=200)),
                ('keywords', models.JSONField(default=list, help_text='List of keywords to match (case-insensitive)')),
                ('exceptions', models.JSONField(default=list, help_text='Keywords whose presence cancels a match')),
                ('scope', models.CharField(choices=[('cve', 'CVE'), ('ransomware', 'Ransomware'), ('both', 'Both')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Watch Rule',
                'verbose_name_plural': 'Watch Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.BooleanField(default=False, verbose_name='E-mail')),
                ('thehive', models.BooleanField(default=False, verbose_name='TheHive')),
                ('slack', models.BooleanField(default=False, verbose_name='Slack')),
                ('citadel', models.BooleanField(default=False, verbose_name='Citadel')),
                ('notify_all_cves', models.BooleanField(default=True, verbose_name='All CVEs')),
                ('notify_cve_hits', models.BooleanField(default=True, verbose_name='CVE Hits')),
                ('notify_all_victims', models.BooleanField(default=True, verbose_name='All Victims')),
                ('notify_victim_hits', models.BooleanField(default=True, verbose_name='Victim Hits')),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_watch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subscribers',
            },
        ),
        migrations.CreateModel(
            name='RansomwareVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('attacked_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=750)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='cyber_watch.ransomwaregroup')),
            ],
            options={
                'verbose_name': 'Ransomware Victim',
                'verbose_name_plural': 'Ransomware Victims',
                'ordering': ['-attacked_at'],
                'unique_together': {('group', 'victim_name', 'attacked_at')},
            },
        ),
        migrations.CreateModel(
            name='WatchRuleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_type', models.CharField(choices=[('cve', 'CVE'), ('ransomware_victim', 'Ransomware Victim')], max_length=20)),
                ('object_id', models.CharField(max_length=500)),
                ('hit_display', models.TextField()),
                ('matched_keyword', models.CharField(max_length=200)),
                ('hit_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='cyber_watch.watchrule')),
            ],
            options={
                'verbose_name': 'Watch Rule Hit',
                'verbose_name_plural': 'Watch Rule Hits',
                'ordering': ['-hit_at'],
                'unique_together': {('rule', 'hit_type', 'object_id', 'matched_keyword')},
            },
        ),
    ]
