# Generated by Django 3.0.5 on 2020-04-17 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100, unique=True)),
                ('rtir', models.IntegerField(default=0, unique=True)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('content_fuzzy_hash', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['domain_name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_monitoring.Site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
