# Generated by Django 3.0.5 on 2020-04-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
