# Generated by Django 3.0.5 on 2020-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0002_auto_20200420_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='rtir',
            field=models.IntegerField(unique=True),
        ),
    ]
