# Generated by Django 3.0.5 on 2020-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0004_auto_20200420_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='content_fuzzy_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
