# Generated by Django 3.0.5 on 2020-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0006_site_ip_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='difference_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='ip_second',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_ip_second',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
