# Generated by Django 3.0.5 on 2020-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0008_auto_20200423_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='monitored',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='web_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
