# Generated by Django 3.0.6 on 2020-05-07 10:47

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0011_auto_20200506_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='mail_domains',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=1010, null=True, size=10),
        ),
    ]
