# Generated by Django 3.0.6 on 2020-05-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0013_auto_20200507_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='mail_domains',
            new_name='mx_records',
        ),
    ]
