# Generated by Django 3.0.6 on 2020-05-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0014_auto_20200507_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='mail_a_record_ip',
            new_name='mail_record_ip',
        ),
    ]
