# Generated by Django 3.0.6 on 2020-05-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0015_auto_20200507_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='mail_record_ip',
            new_name='mail_A_record_ip',
        ),
    ]
