# Generated by Django 3.0.6 on 2020-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0017_auto_20200507_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='content_monitoring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ip_monitoring',
            field=models.BooleanField(default=True),
        ),
    ]
