# Generated by Django 3.0.6 on 2020-05-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0018_auto_20200518_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='web_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
