# Generated by Django 3.1 on 2020-09-02 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_monitoring', '0022_auto_20200831_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_monitoring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
