# Generated by Django 3.1.1 on 2020-09-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0023_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='mail_monitoring',
            field=models.BooleanField(default=True),
        ),
    ]
