# Generated by Django 3.1.1 on 2020-09-10 10:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0024_site_mail_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='new_MX_records',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=1010, null=True, size=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='new_mail_A_record_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_MX_records',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=1010, null=True, size=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_mail_A_record_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
