# Generated by Django 5.0.2 on 2024-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0027_auto_20210517_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='rtir',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
