# Generated by Django 5.0.11 on 2025-06-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0029_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='misp_event_id',
        ),
    ]
