# Generated by Django 5.2.3 on 2025-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0030_remove_site_misp_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='new_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='new_registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='blocking_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='domain_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='legal_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='legitimacy',
            field=models.IntegerField(blank=True, choices=[(1, 'Unknown'), (2, 'Suspicious, not harmful'), (3, 'Suspicious, likely harmful (registered)'), (4, 'Suspicious, likely harmful (available/disabled)'), (5, 'Malicious (registered)'), (6, 'Malicious (available/disabled)')], null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='takedown_request',
            field=models.BooleanField(default=False),
        ),
    ]
