# Generated by Django 5.2.11 on 2026-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0031_alert_new_expiry_date_alert_new_registrar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='new_ssl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_ssl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='domain_created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ssl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
