# Generated by Django 6.0.5 on 2026-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0033_site_udrp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='new_server_banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='new_x_powered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_server_banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='old_x_powered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='server_banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='x_powered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
