# Generated by Django 6.0.5 on 2026-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_monitoring', '0034_banner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='network_history',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
