"""
Django settings for watcher project.

Generated by 'django-admin startproject' using Django 1.11.25.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

import ldap
from django_auth_ldap.config import LDAPSearch
from datetime import timedelta

# LDAP Setup
AUTH_LDAP_SERVER_URI = os.environ.get('AUTH_LDAP_SERVER_URI', "")

# TLS/SSL Certificate Verification
AUTH_LDAP_VERIFY_SSL = os.environ.get('AUTH_LDAP_VERIFY_SSL', 'False')
if AUTH_LDAP_VERIFY_SSL == 'False':
    AUTH_LDAP_GLOBAL_OPTIONS = {ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_NEVER}

AUTH_LDAP_BIND_DN = os.environ.get('AUTH_LDAP_BIND_DN', "")
AUTH_LDAP_BIND_PASSWORD = os.environ.get('AUTH_LDAP_BIND_PASSWORD', "")

AUTH_LDAP_USER_SEARCH = LDAPSearch(os.environ.get('AUTH_LDAP_BASE_DN', ""),
                                   ldap.SCOPE_SUBTREE,
                                   os.environ.get('AUTH_LDAP_FILTER', "(uid=%(user)s)"))

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}

AUTHENTICATION_BACKENDS = (
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! You can set DJANGO_SECRET_KEY environment variable
# to change it within the .env file.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '9t4yzl@%fg*vd-@%jxn%e29v)j_pl_9-qu(onjic((jfca$z(!')
if SECRET_KEY == '':
    SECRET_KEY = '9t4yzl@%fg*vd-@%jxn%e29v)j_pl_9-qu(onjic((jfca$z(!'

# SECURITY WARNING: In production please put DJANGO_DEBUG environment variable to False in the .env file!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOSTS = [
    '0.0.0.0',
    '127.0.0.1',
    'localhost',
] + os.environ.get('ALLOWED_HOSTS', '').split(',')

if os.environ.get('CSRF_TRUSTED_ORIGINS', '') != '':
    CSRF_TRUSTED_ORIGINS = [
        'https://' + os.environ.get('CSRF_TRUSTED_ORIGINS', ''),
        'http://' + os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    ]

# threats_watcher APP settings
# Will use django-constance to store these settings in db

# Feed Parser Configuration
POSTS_DEPTH = 30
WORDS_OCCURRENCE = 5
# Example for daily watch : PostsDepth = 30 et WordsOccurrence = 5
# Example for a continuous watch : PostsDepth = 3 et WordsOccurrence = 8
# Example for a Monday morning watch : PostsDepth = 50 et WordsOccurrence = 0

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('SMTP_SERVER', '') 
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 25))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', False)
if EMAIL_USE_TLS == "True":
    EMAIL_USE_TLS = True
if EMAIL_USE_TLS == "False":
    EMAIL_USE_TLS = False
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', False)
if EMAIL_USE_SSL == "True":
    EMAIL_USE_SSL = True
if EMAIL_USE_SSL == "False":
    EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  
EMAIL_FROM = os.environ.get('EMAIL_FROM', '')  
SUBJECT_TAG_SITE_MONITORING = os.environ.get('SUBJECT_TAG_SITE_MONITORING', 'INCIDENT')
# Display at the end of the email notification
EMAIL_CLASSIFICATION = os.environ.get('EMAIL_CLASSIFICATION', 'Internal')
# Website url, link in e-mails body
WATCHER_URL = os.environ.get('WATCHER_URL', '')
# Watcher Logo
WATCHER_LOGO = os.environ.get('WATCHER_LOGO', '')
GITHUB_LOGO = os.environ.get('GITHUB_LOGO', '')

# Proxy setup
HTTP_PROXY = os.environ.get('HTTP_PROXY', '')
HTTPS_PROXY = os.environ.get('HTTPS_PROXY', '')

# CertStream URL
CERT_STREAM_URL = os.environ.get('CERT_STREAM_URL', 'wss://certstream.calidog.io')

# Link to Searx Server API
DATA_LEAK_SEARX_URL = os.environ.get('DATA_LEAK_SEARX_URL', 'http://searx:8080/')

# The Hive Setup
THE_HIVE_URL = os.environ.get('THE_HIVE_URL', '')
THE_HIVE_VERIFY_SSL = os.environ.get('THE_HIVE_VERIFY_SSL', False)
if THE_HIVE_VERIFY_SSL == "True":
    THE_HIVE_VERIFY_SSL = True
if THE_HIVE_VERIFY_SSL == "False":
    THE_HIVE_VERIFY_SSL = False
THE_HIVE_KEY = os.environ.get('THE_HIVE_KEY', '')
THE_HIVE_CUSTOM_FIELD = os.environ.get('THE_HIVE_CUSTOM_FIELD', 'watcher-id')
THE_HIVE_EMAIL_SENDER = os.environ.get('THE_HIVE_EMAIL_SENDER', 'watcher@watcher.com')
THE_HIVE_TAGS = os.environ.get('THE_HIVE_TAGS', "Watcher,Impersonation,Malicious Domain,Typosquatting").split(",")

# MISP Setup
MISP_URL = os.environ.get('MISP_URL', 'https://cert-misp-dev.corp.thales/')
MISP_VERIFY_SSL = os.environ.get('MISP_VERIFY_SSL', False)
if MISP_VERIFY_SSL == "True":
    MISP_VERIFY_SSL = True
if MISP_VERIFY_SSL == "False":
    MISP_VERIFY_SSL = False
MISP_KEY = os.environ.get('MISP_KEY', 'qY1q8OsRX6HdaQuMKaNzrMKmd1t2GBRaMEb25VFt')
MISP_TICKETING_URL = os.environ.get('MISP_TICKETING_URL', '')
MISP_TAGS = os.environ.get('MISP_TAGS', "Watcher,Impersonation,Malicious Domain,Typosquatting,TLP:Amber").split(",")

# Slack configuration
SLACK_API_TOKEN = os.environ.get('SLACK_API_TOKEN', '')
SLACK_CHANNEL = os.environ.get('SLACK_CHANNEL', '')

# Citadel configuration
CITADEL_API_TOKEN = os.environ.get('CITADEL_API_TOKEN', '')
CITADEL_ROOM_ID = os.environ.get('CITADEL_ROOM_ID', '')
CITADEL_URL = os.environ.get('CITADEL_URL', '')

# Weekly Summary Configuration
WEEKLY_SUMMARY_DAY = os.environ.get('WEEKLY_SUMMARY_DAY', 'Monday')
WEEKLY_SUMMARY_HOUR = os.environ.get('WEEKLY_SUMMARY_HOUR', '09:30')

# Breaking News Configuration
BREAKING_NEWS_THRESHOLD = int(os.environ.get('BREAKING_NEWS_THRESHOLD', 15))

# Application definition
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'threats_watcher',
    'rest_framework',
    'frontend',
    'data_leak',
    'site_monitoring',
    'dns_finder',
    'common',
    'knox',
    'django.contrib.admindocs',
    'accounts',
    'import_export',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':
        ('knox.auth.TokenAuthentication',)
}

REST_KNOX = {
  'SECURE_HASH_ALGORITHM': 'cryptography.hazmat.primitives.hashes.SHA3_512',  
  'TOKEN_TTL': timedelta(hours=10),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'watcher.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'watcher.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# SECURITY WARNING: In production please set DB_USER and DB_PASSWORD environment variables in the .env file.
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.mysql',
       'CONN_MAX_AGE': 3600,
    #    'NAME': 'db_watcher126',
       'NAME': 'db_watcher500',
       'USER': 'watcher',
       'PASSWORD': 'Ee5kZm4fWWAmE9hs!',
       'HOST': 'localhost',
       'PORT': '3306',
       'OPTIONS': {
           'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
       },
   }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TZ', 'Europe/Paris')

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

TRACE_LEVEL = os.environ.get('TRACE_LEVEL', 'INFO')

# Logging configuration
LOGGING = {
    "version": 1,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} | {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'console': {
            'format': '{levelname} {asctime} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
        'file_common': {
            'level': TRACE_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'common.log'),
            'formatter': 'verbose',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
        },
        'file_threats_watcher': {
            'level': TRACE_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'threats_watcher.log'),
            'formatter': 'verbose',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
        },
        'file_data_leak': {
            'level': TRACE_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'data_leak.log'),
            'formatter': 'verbose',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
        },
        'file_dns_finder': {
            'level': TRACE_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'dns_finder.log'),
            'formatter': 'verbose',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
        },
        'file_site_monitoring': {
            'level': TRACE_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'site_monitoring.log'),
            'formatter': 'verbose',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
        },
    },
    "loggers": {
        'watcher.common': {
            'handlers': ['file_common', 'console'], 
            'level': TRACE_LEVEL,
            'propagate': False,
        },
        'watcher.threats_watcher': {
            'handlers': ['file_threats_watcher', 'console'],
            'level': TRACE_LEVEL,
            'propagate': False,
        },
        'watcher.data_leak': {
            'handlers': ['file_data_leak', 'console'],
            'level': TRACE_LEVEL,
            'propagate': False,
        },
        'watcher.dns_finder': {
            'handlers': ['file_dns_finder', 'console'],
            'level': TRACE_LEVEL,
            'propagate': False,
        },
        'watcher.site_monitoring': {
            'handlers': ['file_site_monitoring', 'console'],
            'level': TRACE_LEVEL,
            'propagate': False,
        },
        'watcher': {
            'handlers': ['file_common'],
            'level': TRACE_LEVEL,
            'propagate': False,
        },
    },
    "disable_existing_loggers": False
}

# Maximum upload size in bytes
MAX_UPLOAD_SIZE = 5242880  # 5MB