apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watcher.fullname" . }}
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
    app.kubernetes.io/component: watcher
spec:
  replicas: {{ .Values.watcher.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: watcher
      annotations:
        checksum/secret-env: {{ include (print $.Template.BasePath "/secret-env.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: watcher
          image: "{{ .Values.watcher.image.repository }}:{{ .Values.watcher.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.watcher.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.watcher.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "watcher.fullname" . }}-env
          {{- if or .Values.tlsBundle.certfile .Values.tlsBundle.keyfile }}
          volumeMounts:
            - name: tls-bundle
              mountPath: /etc/private
              readOnly: true
          {{- end }}
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.watcher.service.port }}
            failureThreshold: 24
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.watcher.service.port }}
            periodSeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.watcher.service.port }}
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 10
          {{- with .Values.watcher.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if or .Values.tlsBundle.certfile .Values.tlsBundle.keyfile }}
      volumes:
        - name: tls-bundle
          secret:
            secretName: {{ include "watcher.fullname" . }}-tls-bundle
      {{- end }}
